---
layout: post
title: Promise 相关知识
date: 2019-11-19
tags: [JavaScript]
---

## 传统回调的问题

这里简单介绍一下，传统回调函数存在的问题。

首先，传动回调函数用来解决异步编程的时候，跟我们平常的同步思维不一样，即，我们平常做完一件事，接着做另外一件事，是很有顺序性的。但是回调函数是当某个异步函数成功之后再调用的，我们无法知道它究竟是什么时候执行，这个是“顺序性”的问题。

第二个，就是控制性的问题。当我们使用第三方库来处理回调的时候，可能会出现几种情况：

- 回调过早
- 回调过晚
- 回调函数执行过多，或经过多次传递
- 回调函数传参问题
- 回调函数异常吞并

这些都是我们会遇到的问题。为了解决这些问题，Promise就登场了。

## Promise信任问题

Promise解决了回调函数的信任问题。

### 调用过早

根据定义Promise不必担心这种问题，因为即使是立即完成的Promise（new Promise类的） 也无法被同步观察到。也就是说，对一个Promise调用then的时候即使这个Promise已经决议，提供then的回调也总会被异步调用（涉及到建立于事件队列上的ES6新的概念——任务队列，自行查阅）

### 调用过晚

Promise创建对象调用resolve或者reject时，这个Promise的then注册的观察回掉就会被自动调用。可以确信，这些被调度的回调在下一个tick一定会被触发。

需要注意的是，不应该依赖于不同的Promise间回调的顺序和调度。下面的代码是种反模式。

    let p3 = new Promise (function (resolve, reject) {
        resolve('b');
    })
    let p1 = new Promise (function (resolve, reject) {
        resolve('p3');
    })
    let p2 = new Promise (function (resolve, reject) {
        resolve('a')
    })
    p1.then(function (v) {
        console.log(v)
    })
    p2.then( function (v) {
        console.log(v);
    })
    // a b 

### 回调未调用

首先没有任何东西能够阻止Promise决议的进行。如果Promise注册了resolve或者reject，那它总会执行其中一个。

但是如果Promise永远不被决议，那么可以使用下面的代码来进行检测。称之为 “超时模式”。

    function tiemoutPromise(delay) {
        return new Promise( function (resolve, reject) {
            setTimeout( function () {
                reject("Timeout");
            }, delay)
        })
    }
    Promise.race([
        foo(), // foo也是一个Promise相关的函数，尝试执行foo
        timeoutPromise(3000) // 3秒钟“忍耐”
    ]).then(
        function () {
            // foo()及时完成
        }，
        function (err) {
            // foo() 被拒绝，或者没有按时完成
            // 查看err来了解情况
        }
    )

这段代码是用来解决Promise没有被决议的问题，可以防止foo被永久挂起。

### 调用次数过多

Promise只会被决议一次，不存在多次调用resolve或者reject的情况，如果出现，只会执行第一个，忽略后面的。当然可以多次then。例如这样。

    let p = new Promise(function (resolve, reject) {
        console.log('haha')
    })
    p.then(function () {
        console.log('success')
    }, function () {
        console.log('fail')
    })
    p.then(function () {
        console.log('success1');
    }, function () {
        onsole.log('fail1')
    })

这样的多次调用是可以的，但是通常不会遇到这种业务逻辑，因为这都是可以合并到一个resolve或者reject中的。

### 错误处理

如果一个Promise被reject，这个值会被传给reject回调。但是，如果在决议过程中，JavaScript出现了一个异常，例如一个typeError或者一个referenceError，这个异常就会是这个promise被reject。

但是，如果Promise完成后在then的回调中出现异常会怎样了？

    let p = new Promise (function (resolve, reject) {
        resolve(42);
    })
    p.then(
        function fulfilled(msg) {
            foo.bar();
            cosnole.log(msg) // 不会到这了，forever
        },
        function rejected(err) {
            // 不会到这里，forever
        }
    )

这个时候的报错，我们就没有监听到了，但是，我们可以使用catch来捕获这个错误，同样是可以解决的。

### 信任问题

这里可以看出，Promise并没有完全摆脱回调，它只是改变了传递回调的位置。但是，Promise解决了单纯的回调的信任问题，通过Promise.resolve()。

如果想Promise.resolve传递一个非Promise、非thenable的立即值，就会得到一个以这个值填充的Promise。下面这种情况，promise1和promise2行为是一致的：

    let p1 = new Promise (function (resolve, reject) {
        resolve(42);
    })
    let p2 = Promise.resolve(42)

更重要的是当Promise.resolve传递一个非Promise的thenable值前者会试图展开这个值，而且展开过程会持续提取到一个具体的非类Promise中的最终值。Promise.resolve可以接受任何thenable，将其封装为它的非thenable值。从Promise.resolve得到的是一个真正的Promise，是一个可以信任的值。

当我们需要调用一个工具foo的时候，并不确定他是否是一个可靠地Promise，我们知道它至少是一个thenable。那么可以这样操作。

    foo(41)
    .then(function (v) {
        console.log(v)
    }) // do not handle like it 

    Promise.resolve(foo(42))
            .then(function (v) {
                console.log(v)
            }) // good example
        

Promise这种模式通过可信任的语义把回调作为参数传递，使得这种行为更加可靠合理。通过把回调的控制反转反转回来，把控制权放在一个可信任的系统中。这样可以使异步编码更加清晰。！！

这部分就先总结到这，希望大家能有所收获！